first commit
zaid-malek-simform/php-converter pull request #1
Opened 2023-03-16 13:17 UTC by zaid0malek

2023-03-16 13:44 UTC, dhavalmistrysimform requested changes
Please work on the given comments

2023-03-16 13:44 UTC, dhavalmistrysimform commented on Length.php
> +  // $val2=$_POST['val2'];
Remove this unwanted commented code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on Length.php
> +  <div class="modal " id="lengthModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
Remove extra space after model

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on area.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this unwanted code.

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on area.php
> +  <!-- partial:index.partial.html -->
Remove this code.

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on conversion.php
> +function len($val,$from,$to){
Provide function description and curly brackets must be in next line.

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on conversion.php
> +    $meter=toMeter($val,$from);
Provide spacing between equal to and add space after like this $val, $from

2023-03-16 13:44 UTC, dhavalmistrysimform commented on conversion.php
> +    echo fromMeter($meter,$to);
Add space after $meter,

2023-03-16 13:44 UTC, dhavalmistrysimform commented on conversion.php
> +if(isset($_POST['type'])){
Make sure you do the changes for this file.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on css/demo.css
> +/* @media only screen and (min-width: 720px) {
Remove this code

2023-03-16 13:44 UTC, dhavalmistrysimform commented on css/style.css
> +} */
Remove this code.

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on css/style.css
> +  /* flex-wrap: wrap; */
Remove this code.

2023-03-16 13:44 UTC, dhaval-mistry-simform commented on css/style.css
> +  /* z-index: -2; */
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on css/style.css
> +  /* font-smoothing: antialiased; */
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on css/style.css
> +   }
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on css/style.css
> +  /* height: 40rem; */
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on currency.php
> +    $req_url = "https://api.exchangerate-api.com/v4/latest/$from";
Variable name should be camelCased.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on currency.php
> +if(isset($_POST['submit'])){
Please format the document properly

2023-03-16 13:44 UTC, dhavalmistrysimform commented on currency.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on currency.php
> +  <!-- partial:index.partial.html -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on currency.php
> +                <!-- <input type="hidden" class="form-control" id="type" name="type" value="volume"> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on index.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on index.php
> +              </div> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on js/script.js
> +            // debugger;
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on js/script.js
> +    opt1 = $("#opt1").val();
Provide variable is let, var, const.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on mail.php
> +    // echo"here";
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on mail.php
> +// phpinfo();
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on mail.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on numbers.php
> +if(isset($_POST['submit'])){
Please format this

2023-03-16 13:44 UTC, dhavalmistrysimform commented on numbers.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this code.

2023-03-16 13:44 UTC, dhavalmistrysimform commented on speed.php
> +  <!-- <link rel="stylesheet" href="css/demo.css"> -->
Remove this code.

2023-03-17 05:57 UTC, dhavalmistrysimform requested changes
Please work on given comments

2023-03-17 05:57 UTC, dhavalmistrysimform commented on conversion.php
> +}
Add new line after this

2023-03-17 05:57 UTC, dhavalmistrysimform commented on conversion.php
> +}
Add new line after this

2023-03-17 05:57 UTC, dhavalmistrysimform commented on conversion.php
> +}
Add new line after this

2023-03-17 05:57 UTC, dhavalmistrysimform commented on conversion.php
> +}
General Comment: Add new line after every function.

2023-03-17 05:57 UTC, dhavalmistrysimform commented on conversion.php
> +    switch($_POST['type']){
Add space after switch and before opening curly braces

2023-03-17 05:57 UTC, dhavalmistrysimform commented on currency.php
> +      // Try/catch for json_decode operation
Remove this unwanted code.

2023-03-17 05:57 UTC, dhavalmistrysimform commented on mail.php
> +if(isset($_POST['submit'])){
Format this document perfectly. Make sure you provide required spacing.
for eg. **if (isset($_POST['submit'])) {**

2023-03-17 06:52 UTC, dhavalmistrysimform requested changes
Please work on given comments

2023-03-17 06:52 UTC, dhavalmistrysimform commented on conversion.php
> +    $meter=toSqMeter($val, $from);
Add spacing between =

2023-03-17 06:52 UTC, dhavalmistrysimform commented on conversion.php
> +    $kilo=toKMPH($val, $from);
Add spacing between =

2023-03-17 06:52 UTC, dhavalmistrysimform commented on mail.php
> +    $to=$_POST['to'];
Add spacing between =

2023-03-17 11:27 UTC, dhavalmistrysimform requested changes
Please work on the given comments.

2023-03-17 11:27 UTC, dhavalmistrysimform commented on currency.php
> +  $value=$_POST['val1'];
Add spacing between =

2023-03-17 11:27 UTC, dhavalmistrysimform commented on js/script.js
> +$(".btn").click(function () {
Place this code inside document.ready or IIFE

2023-03-17 11:27 UTC, dhavalmistrysimform commented on numbers.php
> +  $value=$_POST['val1'];
Please format this.

2023-03-17 12:23 UTC, dhavalmistrysimform requested changes
Work on given comments

2023-03-17 12:23 UTC, dhavalmistrysimform commented on numbers.php
> +if( isset($_POST['submit']) ){
it should be like this if (isset($_POST['submit'])) {

2023-04-10 08:48 UTC, merged